### ISSUE TITLE
Statistics: Choosing “branch” in any of the mode-dropdowns gives a tskit.LibraryError

### ISSUE THREAD

**Issue by hannamlmv** [hannamlmv/tseda#8]
Choosing “branch” in any of the mode-dropdowns gives a tskit.LibraryError
This should be fixed.

**Error message:**

ERROR: panel.reactive - Callback failed for object named 'Mode' changing property {'value': 'branch'} 
Traceback (most recent call last):
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 536, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 1031, in update_pane
    self._replace_pane()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 1054, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/src/tseda/vpages/stats.py", line 85, in __panel__
    data = self.datastore.tsm.ts.diversity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7995, in diversity
    return self.__one_way_sample_set_stat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7702, in __one_way_sample_set_stat
    stat = self.__run_windowed_stat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7664, in __run_windowed_stat
    stat = method(*args, **kwargs, windows=windows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tskit.LibraryError: Statistics using branch lengths cannot be calculated when time_units is 'uncalibrated'. (TSK_ERR_TIME_UNCALIBRATED)
2024-11-15 13:02:34,225 [73764] ERROR    tornado.application: Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x12b1fee10>>, <Task finished name='Task-1248' coro=<ServerSession.with_document_locked() done, defined at /Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/bokeh/server/session.py:77> exception=LibraryError("Statistics using branch lengths cannot be calculated when time_units is 'uncalibrated'. (TSK_ERR_TIME_UNCALIBRATED)")>)
Traceback (most recent call last):
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
             ^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/reactive.py", line 509, in _change_coroutine
    state._handle_exception(e)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/io/state.py", line 468, in _handle_exception
    raise exception
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/reactive.py", line 507, in _change_coroutine
    self._change_event(doc)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/reactive.py", line 525, in _change_event
    self._process_events(events)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 536, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 1031, in update_pane
    self._replace_pane()
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/panel/param.py", line 1054, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/src/tseda/vpages/stats.py", line 85, in __panel__
    data = self.datastore.tsm.ts.diversity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7995, in diversity
    return self.__one_way_sample_set_stat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7702, in __one_way_sample_set_stat
    stat = self.__run_windowed_stat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannamalmvall/Library/CloudStorage/OneDrive-Uppsalauniversitet/År 5/Slutkurs/tseda/.venv/lib/python3.12/site-packages/tskit/trees.py", line 7664, in __run_windowed_stat
    stat = method(*args, **kwargs, windows=windows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tskit.LibraryError: Statistics using branch lengths cannot be calculated when time_units is 'uncalibrated'. (TSK_ERR_TIME_UNCALIBRATED)

**Comment by hannamlmv** [comment]
question: what is the branch mode supposed to do?

**Comment by percyfal** [comment]
In Python, given a tree sequence `ts`, you can check whether the tree sequence is calibrated by inspecting `ts.time_units`. If the tree is uncalibrated, on could hide the `branch` option from the dropdown list.

**Comment by hannamlmv** [comment]
<img width="651" alt="Skärmavbild 2024-11-25 kl  12 52 41" src="https://github.com/user-attachments/assets/2ed26730-490e-4795-b1db-27a13112aae3">
